# NOTE: In doc/source/contributor/testing/ci_scenario_jobs.rst file there is
# document with summary of all tempest, neutron-tempest-plugin and grenade jobs
# summary.
# Please update this document always when any changes to jobs are made.
- project:
    templates:
      - neutron-tempest-plugin-jobs-xena
      - openstack-cover-jobs
      - openstack-python3-xena-jobs
      - openstack-python3-xena-jobs-arm64
      - publish-openstack-docs-pti
      - periodic-stable-jobs
      - check-requirements
      - release-notes-jobs-python3
    check:
      jobs:
        - neutron-functional-with-uwsgi
        - neutron-fullstack-with-uwsgi
        - neutron-ovs-rally-task
        - neutron-ovs-grenade-multinode
        - neutron-ovs-grenade-dvr-multinode:
            # TODO(slaweq): make that job voting when bug
            # https://bugs.launchpad.net/neutron/+bug/1920778
            # will be fixed
            voting: false
        - neutron-ovs-tempest-multinode-full
        - neutron-ovs-tempest-dvr-ha-multinode-full
        - neutron-ovn-tempest-ipv6-only
        # TODO(slaweq): add this job again to the check queue when it will be
        # working fine on python 3
        #- networking-midonet-tempest-aio-ml2-centos-7:
        #    voting: false
        - neutron-ovn-rally-task:
            voting: false
        - openstack-tox-py36:  # from openstack-python3-xena-jobs template
            timeout: 3600
        - openstack-tox-py38:  # from openstack-python3-xena-jobs template
            timeout: 3600
        - openstack-tox-cover:  # from openstack-cover-jobs template
            timeout: 4800
    gate:
      jobs:
        - neutron-functional-with-uwsgi
        - neutron-fullstack-with-uwsgi
        - neutron-ovs-tempest-multinode-full
        - neutron-ovs-grenade-multinode
        # TODO(slaweq): make that job gating when bug
        # https://bugs.launchpad.net/neutron/+bug/1920778
        # will be fixed
        # - neutron-ovs-grenade-dvr-multinode
        - neutron-ovn-tempest-ipv6-only
        - openstack-tox-py36:  # from openstack-python3-xena-jobs template
            timeout: 3600
        #- neutron-ovn-rally-task

    experimental:
      jobs:
        - neutron-functional-with-uwsgi-fips
        - neutron-fullstack-with-uwsgi-fips
        - neutron-ovs-tempest-fips
        - neutron-ovn-tempest-ovs-release-fips
        - neutron-ovn-grenade-multinode
        - neutron-ovn-tempest-with-uwsgi-loki

    periodic:
      jobs:
        - neutron-functional
        - neutron-fullstack
        - neutron-ovn-tempest-postgres-full
        - neutron-ovn-tempest-mariadb-full
        - neutron-ovn-tempest-ovs-release
        - neutron-ovn-tempest-ovs-release-ipv6-only
        - devstack-tobiko-neutron:
            voting: true
        - ironic-tempest-ipa-wholedisk-bios-agent_ipmitool-tinyipa
        - openstacksdk-functional-devstack-networking
        - neutron-linuxbridge-tempest-plugin-scenario-nftables
        - neutron-ovs-tempest-plugin-scenario-iptables_hybrid-nftables
